#ifndef INTRO_H_INCLUDED
#define INTRO_H_INCLUDED
#include <stdlib.h>
#include <iostream>
#include <windows.h>
using namespace std;
void into()
{
    //one
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);

    cout << "                                             \n";
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    //two
    system("CLS");
    Sleep(10);
    cout << "                                             \n";
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);
    cout << "                                             \n";
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);
    cout << "                                             \n";
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);
    //three
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);

    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(10);
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "          The Triple Entente                 \n";
    cout << "                                             \n";
    cout << "                                             \n";
    cout << "                                             \n";

    system("CLS");
    Sleep(1000);
}


#endif // INTRO_H_INCLUDED
